# axi_spi_dac.xdc
# Constraints for the DAC80508 SPI Interface using the AXI Quad SPI IP on ZMOD B

# NOTE: The port names below assume the top-level ports of the Block Design
#       are named according to the external signals generated by the AXI Quad SPI core.
#       e.g., spi_sclk_o, spi_ss_o, spi_io0_o (MOSI)

# ------------------------------------------------------------------
# ZMOD B: DAC SPI Interface Pin Assignments (LVCMOS18)
# ------------------------------------------------------------------
# Constrain the SPI Clock pin (SCLK) to the ZMOD B pin S3_D3P
set_property PACKAGE_PIN AB14 [get_ports spi_multidac_dac_sck_io] 
set_property IOSTANDARD LVCMOS18 [get_ports spi_multidac_dac_sck_io]

# Slave Select Output (CS_N) - Mapped to S3_D3N
set_property PACKAGE_PIN AB15 [get_ports spi_multidac_dac_ss_io[0]]
set_property IOSTANDARD LVCMOS18 [get_ports spi_multidac_dac_ss_io[0]]

# Serial Data Out (MOSI/SDI) - Mapped to S1_D1P
set_property PACKAGE_PIN V13 [get_ports spi_multidac_dac_io0_io]
set_property IOSTANDARD LVCMOS18 [get_ports spi_multidac_dac_io0_io]

# Serial Data In (MISO/SDO) - Mapped to S1_D1N
set_property PACKAGE_PIN W13 [get_ports spi_multidac_dac_io1_io] 
set_property IOSTANDARD LVCMOS18 [get_ports spi_multidac_dac_io1_io]


# ------------------------------------------------------------------
# ZMOD A - LTC2264-12 (4-Wire SPI) CONSTRAINTS
# ------------------------------------------------------------------
# Constrain the SPI Clock pin (SCLK) to the ZMOD A pin S12_D6P
set_property PACKAGE_PIN J18 [get_ports spi_adc_sck_io] 
set_property IOSTANDARD LVCMOS18 [get_ports spi_adc_sck_io]

# Slave Select Output (CS_N) - Mapped to S10_D4N
set_property PACKAGE_PIN R16 [get_ports spi_adc_ss_io[0]]
set_property IOSTANDARD LVCMOS18 [get_ports spi_adc_ss_io[0]]

# Serial Data Out (MOSI/SDI) - Mapped to S8_D4P
set_property PACKAGE_PIN P16 [get_ports spi_adc_io0_io]
set_property IOSTANDARD LVCMOS18 [get_ports spi_adc_io0_io]

# Serial Data In (MISO/SDO) - Mapped to S14_D6N
set_property PACKAGE_PIN K18 [get_ports spi_adc_io1_io] 
set_property IOSTANDARD LVCMOS18 [get_ports spi_adc_io1_io]
